/**
 * Cross-language test vectors: the TypeScript engine replays fixed dice
 * streams generated by the Python reference engine and must produce the
 * identical event stream.
 *
 * Fixtures live in `tests/crosslang/fixtures/` (repo root) and are
 * generated by `tests/crosslang/generate_fixtures.py`, which runs the
 * Python engine on explicit dice. Because both sides play *explicit*
 * dice, the PRNG difference (Mersenne Twister vs mulberry32) is
 * irrelevant — these vectors pin the *rules*: payouts, phase
 * transitions, odds, stop-loss/win, ruin, and the event schema itself.
 *
 * Regenerate fixtures after any intentional rules change, then re-run.
 */
import * as fs from "fs";
import * as path from "path";
import { watchSession, type WatchOptions } from "../sim";

const FIXTURES_DIR = path.join(
  __dirname,
  "..",
  "..",
  "..",
  "tests",
  "crosslang",
  "fixtures"
);

interface Fixture {
  name: string;
  config: WatchOptions;
  dice: [number, number][];
  events: Record<string, unknown>[];
}

/** Deep comparison with an epsilon for floating-point fields. */
function expectCloseTo(actual: unknown, expected: unknown, ctx: string): void {
  if (typeof actual === "number" && typeof expected === "number") {
    if (!(Math.abs(actual - expected) <= 1e-9)) {
      throw new Error(`${ctx}: ${actual} not within 1e-9 of ${expected}`);
    }
    return;
  }
  if (Array.isArray(actual) && Array.isArray(expected)) {
    expect(actual.length).toBe(expected.length);
    actual.forEach((a, i) => expectCloseTo(a, expected[i], `${ctx}[${i}]`));
    return;
  }
  if (
    actual !== null &&
    expected !== null &&
    typeof actual === "object" &&
    typeof expected === "object"
  ) {
    const aKeys = Object.keys(actual as object).sort();
    const eKeys = Object.keys(expected as object).sort();
    expect(aKeys).toEqual(eKeys);
    for (const k of aKeys) {
      expectCloseTo(
        (actual as Record<string, unknown>)[k],
        (expected as Record<string, unknown>)[k],
        `${ctx}.${k}`
      );
    }
    return;
  }
  expect(actual).toBe(expected);
}

const fixtureNames = fs
  .readdirSync(FIXTURES_DIR)
  .filter((f) => f.endsWith(".json"))
  .sort();

expect(fixtureNames.length).toBeGreaterThan(0);

for (const file of fixtureNames) {
  test(`cross-language vector: ${file.replace(/\.json$/, "")}`, () => {
    const fixture: Fixture = JSON.parse(
      fs.readFileSync(path.join(FIXTURES_DIR, file), "utf8")
    );
    const actual = [...watchSession({ ...fixture.config, dice: fixture.dice })];
    expect(actual.length).toBe(fixture.events.length);
    actual.forEach((event, i) => {
      const expected = fixture.events[i];
      expect(event.type).toBe(expected["type"]);
      expectCloseTo(event, expected, `event ${i} (${event.type})`);
    });
  });
}
